class SeminaCommissioningError(Exception):
    code = "SEMINA_COMMISSIONING_FAILED"


class InvalidSeminaCommandError(SeminaCommissioningError): code = "SEMINA_INPUT_INVALID"
class InvalidPhysicalStartError(InvalidSeminaCommandError): code = "PHYSICAL_START_INVALID"
class InvalidSeminaOriginError(InvalidSeminaCommandError): code = "SEMINA_ORIGIN_INVALID"
class SeminaIdentityUnavailableError(SeminaCommissioningError): code = "SEMINA_IDENTITY_UNAVAILABLE"
class SeminaIdempotencyConflictError(SeminaCommissioningError): code = "SEMINA_IDEMPOTENCY_CONFLICT"
class SeminaReconciliationRequiredError(SeminaCommissioningError): code = "SEMINA_RECONCILIATION_REQUIRED"
class SeedLotNotFoundError(SeminaCommissioningError): code = "LSE_NOT_FOUND"
class SeedLotVersionConflictError(SeminaCommissioningError): code = "LSE_VERSION_CONFLICT"
class InsufficientSeedError(SeminaCommissioningError): code = "LSE_INSUFFICIENT_SEED"
class IncompatibleSeedLotError(SeminaCommissioningError): code = "LSE_INCOMPATIBLE"
class ExpiredSeedLotError(SeminaCommissioningError): code = "LSE_EXPIRED"
class AnomalousSeedLotError(SeminaCommissioningError): code = "LSE_ANOMALY_BLOCKED"
class ProtocolUnavailableError(SeminaCommissioningError): code = "PROTOCOL_NOT_FOUND_OR_UNAVAILABLE"
class ProtocolContextIncompatibleError(SeminaCommissioningError): code = "PROTOCOL_CONTEXT_INCOMPATIBLE"
class PlanningLineNotFoundError(SeminaCommissioningError): code = "RPS_NOT_FOUND"
class PlanningLineVersionConflictError(SeminaCommissioningError): code = "RPS_VERSION_CONFLICT"
class PlanningLineStateError(SeminaCommissioningError): code = "RPS_STATE_INCOMPATIBLE"
class PlanningQuantityExceededError(SeminaCommissioningError): code = "RPS_QUANTITY_EXCEEDED"
class SeminaCommitRolledBackError(SeminaCommissioningError): code = "SEMINA_COMMIT_ROLLED_BACK"
class SeminaCommitOutcomeUncertainError(SeminaReconciliationRequiredError): code = "SEMINA_COMMIT_OUTCOME_UNCERTAIN"
