from typing import Protocol

from .models import CommissionCustomer, CommissionSupplyProgram, CommissionVariety, OnboardingResult


class OperationalDataOnboardingWriter(Protocol):
    def commission_customer(self, command: CommissionCustomer) -> OnboardingResult: ...
    def commission_variety(self, command: CommissionVariety) -> OnboardingResult: ...
    def commission_supply_program(self, command: CommissionSupplyProgram) -> OnboardingResult: ...
